abstract: Configure your
author: Jonathan Rockway <jrockway@cpan.org
build_requires: 
  Test::More: 0
distribution_type: module
generated_by: Module::Install version 0.64
license: Perl
name: Catalyst-Plugin-ConfigLoader-Environment
no_index: 
  directory: 
    - inc
    - t
requires: 
  Catalyst: 5.7000
version: 0.01
